# makefile para corregir la actividad 3
# make <num_actividad> URL="<url al raw del fichero python>"
1:
	# curl --silent ${URL} | python - -1
	curl --silent ${URL} | python - 12   # NO PRIMO
	curl --silent ${URL} | python - 23   # PRIMO
2:
	# curl --silent ${URL} | python - -1
	curl --silent ${URL} | python - 5   # Resultado: 55
3:
	curl --silent ${URL} | python - 24 18	# Resultado: 6
4:
	# curl --silent ${URL} | python - -1
	curl --silent ${URL} | python - 7   # Resultado: 5040
